name: PR Review with AI

on:
  pull_request:
    types: [opened, synchronize, reopened] # 监听 PR 被创建、更新或重新打开的事件

jobs:
  review:
    runs-on: ubuntu-latest  # 在 GitHub 的 Ubuntu 虚拟环境上运行
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # 设置 Python 环境

      - name: Install dependencies
        run: |
          pip install requests  # 安装 requests 库用于 API 请求
          pip install openai  # 如果你使用 OpenAI API 或其他 AI 工具，可以在这里安装

      - name: Analyze PR changes and post comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动提供的 Token，具有基本的权限
        run: |
          # 获取 PR 的信息
          PR_NUMBER=${{ github.event.pull_request.number }}
          OWNER=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}
          API_URL="https://api.github.com/repos/${OWNER}/${REPO}/pulls/${PR_NUMBER}"

          # 使用 curl 获取 PR 详情
          PR_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $API_URL)

          # 提取 PR 标题和修改内容（可根据需要修改）
          PR_TITLE=$(echo $PR_INFO | jq -r '.title')
          PR_BODY=$(echo $PR_INFO | jq -r '.body')
          PR_CHANGES_URL=$(echo $PR_INFO | jq -r '.url')

          # 假设你有一个 AI 模型分析改动并生成评论
          COMMENT="感谢提交 PR！\n\n### 需要注意的修改建议：\n- 请确保代码符合项目风格\n- 可以考虑优化XXX部分"

          # 通过 GitHub API 提交评论
          COMMENT_API_URL="https://api.github.com/repos/${OWNER}/${REPO}/issues/${PR_NUMBER}/comments"
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" -d "{\"body\": \"$COMMENT\"}" $COMMENT_API_URL
